-- ─────────────────────────────────────────────────────────────────────────────
-- 088 — Add discriminant column `origin` on prospect_emails
--
-- WHY (link to sim finding C1, 28/07/2026):
--   app/api/inbox/messages/[id]/reply/route.ts:158-177 inserts the outbound
--   copy of an inbox reply into prospect_emails, inheriting prospect_id and
--   campaign_step_id from the parent send row. prospect_emails has
--   UNIQUE(prospect_id, campaign_step_id) — non-partial (000_baseline.sql:
--   prospect_emails_prospect_id_campaign_step_id_key) — so the second row on
--   the same (prospect, step) crashes at 23505. Route logs but returns 200
--   (route.ts:179-189), so a real email goes out and Mirvo has no record.
--
--   The chosen fix is a discriminant column that separates the two intents,
--   letting migration 089 replace the constraint with a UNIQUE PARTIAL index
--   restricted to campaign rows. Reply copies then live alongside their
--   campaign siblings on the same (prospect_id, campaign_step_id) without
--   conflict.
--
-- COLUMN CHOICE — `origin` (not `type`, not `source`, not `kind`) :
--   - `type` clashes with future OPENAPI schema tooling (reserved-ish).
--   - `source` collides with prospects.source / deals.source semantic
--     (external attribution, "csv_import" / "manual" / "campaign_reply"…).
--   - `kind` is too generic and reads as an internal implementation flag.
--   - `origin` reads as "who authored this row" — matches the DB doctrine
--     of prospect-authored vs Mirvo-authored intent, and never gets
--     confused with the vendor-taint columns (provider / thread_id /
--     provider_message_id) which are provider-authored.
--
-- VALUES :
--   'campaign'    — generated by draft-generation.ts / variant convergence.
--                   All historical rows fall here (default).
--   'inbox_reply' — outbound copy persisted by
--                   app/api/inbox/messages/[id]/reply/route.ts after the
--                   provider send.
--
-- BEHAVIOUR OF THIS MIGRATION IN PROD :
--   NONE. `ADD COLUMN ... DEFAULT '<constant>' NOT NULL` is a metadata-only
--   operation from PG 11 onwards (constant default, no table rewrite). All
--   existing rows resolve to 'campaign' — the intended, existing meaning.
--   Every current writer omits the column → default applies → identical
--   pre/post behaviour. This migration ships BEFORE any code change; if the
--   B1 PR is reverted, this migration remains a safe no-op.
--
-- IDEMPOTENCE : ADD COLUMN IF NOT EXISTS + ADD CONSTRAINT IF NOT EXISTS.
-- Rejouable sans effet.
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE public.prospect_emails
  ADD COLUMN IF NOT EXISTS origin text NOT NULL DEFAULT 'campaign';

-- CHECK constraint — the pair of valid values, enforced at write time.
-- Uses DO $$ … EXCEPTION to stay idempotent (Postgres has no
-- `ADD CONSTRAINT IF NOT EXISTS` on CHECKs pre-PG 17).
DO $$
BEGIN
  ALTER TABLE public.prospect_emails
    ADD CONSTRAINT prospect_emails_origin_check
    CHECK (origin IN ('campaign', 'inbox_reply'));
EXCEPTION WHEN duplicate_object THEN
  NULL;
END $$;

-- Documentation column comment.
COMMENT ON COLUMN public.prospect_emails.origin IS
  'Discriminant introduced by migration 088. campaign = row created by draft-generation.ts or variant convergence (default, all pre-088 rows). inbox_reply = outbound copy of an inbox reply persisted by app/api/inbox/messages/[id]/reply/route.ts. Feeds the UNIQUE PARTIAL index of migration 089 that scopes convergence unicity to campaign rows.';
